[package]
name = "acp-nats"
version = "0.1.0"
edition = "2024"

[dependencies]
agent-client-protocol = "0.9.4"
async-nats = "0.45.0"
async-trait = "0.1.89"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["rt", "macros", "sync", "time"] }
tracing = "0.1.44"

trogon-nats = { path = "../trogon-nats" }

[dev-dependencies]
trogon-nats = { path = "../trogon-nats", features = ["test-support"] }
