[package]
name = "slack-bot"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "slack-bot"
path = "src/main.rs"

[dependencies]
async-nats = "0.45.0"
futures = "0.3"
slack-morphism = { version = "2", features = ["hyper"] }
slack-nats = { path = "../slack-nats" }
slack-types = { path = "../slack-types" }
tokio = { version = "1.49.0", features = ["full"] }
trogon-nats = { path = "../trogon-nats" }
trogon-std = { path = "../trogon-std" }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0.149"
