[package]
name = "trogon-nats"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
async-nats = "0.45.0"
bytes = "1"
opentelemetry = "0.31.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["time"] }
tracing = "0.1.44"
tracing-opentelemetry = "0.32.1"
trogon-std = { path = "../trogon-std" }

[dev-dependencies]
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
trogon-std = { path = "../trogon-std", features = ["test-support"] }

[features]
default = []
test-support = []
