[package]
name = "telegram-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
telegram-types = { path = "../telegram-types" }
telegram-nats = { path = "../telegram-nats" }
teloxide = { version = "0.14", features = ["macros", "webhooks-axum"] }
async-nats = "0.45"
tokio = { version = "1.49", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5", features = ["derive", "env"] }
anyhow = "1.0"
thiserror = "2.0"
chrono = "0.4.43"
axum = "0.7"
url = "2.5"
mime = "0.3"
reqwest = "0.12"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
