[package]
name = "slack-nats"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.45.0"
serde = "1"
serde_json = "1.0.149"
slack-types = { path = "../slack-types" }
trogon-nats = { path = "../trogon-nats" }

[dev-dependencies]
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
trogon-nats = { path = "../trogon-nats", features = ["test-support"] }

[features]
default = []
test-support = []
